<?php

return [
	'default_locale' => app()->getLocale(),
	'locales' => [
		'cs' => 'cs',
		'en' => 'en',
	],
	'model' => \Bistroagency\Imaginator\Models\Imaginator::class,
	'routes' => [
		'prefix' => 'imaginator',
		'as' => 'imaginator.',
		'middlewares' => [
			'web',
		],
	],
	'storage' => [
		'tempDestination' => public_path('storage/imaginator/tmp/'),
		'destination' => public_path('storage/imaginator/'),
	],
	'breakpoints' => [
		't' =>'tiny',
		's' => 'small',
		'm' => 'medium',
		'l' => 'large',
		'xl' => 'xlarge',
		'xxl' => 'xxlarge',
		'fhd' => 'fullhd',
	],
	'breakpoint_sizes' => [
		'tiny' => '0px',
		'small' => '540px',
		'medium' => '768px',
		'large' => '1004px',
		'xlarge' => '1260px',
		'xxlarge' => '1600px',
		'fullhd' => '1920px',
	],
	'densities' => [
		'regular' => [
			'scale' => 1,
			'suffix' => null,
		],
		'retina' => [
			'scale' => 2,
			'suffix' => '@2',
		],
	],
	'anchor_points' => [
		'tl' => 'top-left',
		't' => 'top',
		'tr' => 'top-right',
		'l' => 'left',
		'c' => 'center',
		'r' => 'right',
		'bl' => 'bottom-left',
		'b' => 'bottom',
		'br' => 'bottom-right',
	],
	/*
	 * Any attributes in this array will be allowed onto the <picture> tag
	 * generated by the generateImagiantorPicture static function.
	 */
	'allowedPictureAttributes' => [
		'class',
		'id',
	]
];